version: '2'
services:
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server --port 3000 -b '0.0.0.0'"
    ports:
      - "3001:3000"
    environment:
      DB_HOST: db
    links:
      - db
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3307:3306"
