version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  api:
    build: .
    command: bundle exec rails server --port 3000 -b 0.0.0.0
    ports:
      - "3001:3000"
    environment:
      DB_NAME: api_development
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
    links:
      - db
    volumes:
      - .:/app
    depends_on:
      - db
